<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIkCvwms\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIkCvwms/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIkCvwms.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIkCvwms\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerIkCvwms\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'IkCvwms',
    'container.build_id' => '9f34f68a',
    'container.build_time' => 1520221229,
));
